Web04/Models/Album.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace Web04.Models {
  public class Album : MusicItem {

    public Album() {
      Songs = new HashSet<Song>();
    } 

    public string Artist { get; set; }

    public string CoverImageUrl { get; set; }

    // navigation properties
    public ICollection<Song> Songs { get; set; }
     
    public TimeSpan TotalLength => TimeSpan.FromSeconds(Songs.Sum(x => x.Length.TotalSeconds));
  }
}

Web04/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Web04.Controllers
{
    public class AlbumsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web04/ViewComponents/SongListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web04.Data;

namespace Web04.ViewComponents {
  public class SongListViewComponent : ViewComponent {

    public SongListViewComponent(ApplicationDbContext db) {
      Db = db;
    }

    public ApplicationDbContext Db { get; }

    public async Task<IViewComponentResult> InvokeAsync(int albumId) {
      var album = Db.Albums.Find(albumId);
      await Db.Entry(album).Collection(x => x.Songs).LoadAsync();
      // await Db.Entry(album).Reference(x => x.SongWriter).LoadAsync();

      return View(album.Songs.ToList());
    }

  }
}

Web04/ViewComponents/SongViewComponent.cs
using Microsoft.AspNetCore.Mvc; 
using Web04.Models;

namespace Web04.ViewComponents {
  public class SongViewComponent : ViewComponent {

    public IViewComponentResult Invoke(Song song) {
      return View(song);
    }
  }
}

Web04/Views/Shared/Components/Album/Default.cshtml
@model Album

<div class="panel panel-default">
  <div class="panel-body">

    <div class="row">
      <div class="col-xs-4">
        <img src="~/images/@Model.CoverImageUrl"
             class="img-responsive img-rounded pull-left" />
      </div>
      <div class="col-xs-8">
        <h3 style="margin-top: 0px;">@Model.Title</h3>
        <vc:song-list album-id="@Model.Id"/>
      </div>
    </div>
  </div>
</div>